version: 2
updates:
  - package-ecosystem: "github-actions"
    directroies:
      - "/"
      - "{{ cookiecutter.package_name }}/.github/workflows"
    directory: "/"
    schedule:
      interval: "weekly"
