name: Run template tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: test-oldestdeps-xdist
          python-version: 3.8
        - linux: test-xdist
          python-version: 3.8
        - linux: test-xdist
          python-version: 3.9
        - linux: test-xdist
          python-version: 3.10
        - linux: test-xdist
          python-version: 3.11
        - linux: test-cov-xdist
          coverage: codecov
